SHELL = /bin/bash
default: lab2_add.c lab2_list.c SortedList.c
	gcc -g -pthread -Wall lab2_add.c -o lab2_add -lrt
	gcc -o lab2_list -g lab2_list.c SortedList.c  -pthread -lrt -Wall

build: lab2_add.c lab2_list.c SortedList.c
	gcc -g -pthread -Wall lab2_add.c -o lab2_add -lrt
	gcc -o lab2_list -g lab2_list.c SortedList.c  -pthread -lrt -Wall

graphs:
	/u/cs/grad/zhou/iloveos/gnuplot lab2_add.gp
	/u/cs/grad/zhou/iloveos/gnuplot lab2_list.gp

make clean:
	@rm -rf *~ lab2_add lab2_list *.o *.txt
#make tarball:
#	@tar 0cvzf lab2a-904299916.tar.gz lab2_add.c SortList.h SortedList.c Makefile lab2_add.csv lab2_list.csv lab2_add-1.png lab2_add-2.png lab2_add-3.png lab2_add-4.png lab2_add-5.png lab2_list-1.png lab2_list-2.png lab2_list-3.png lab2_list-4.png README.txt

tests:	lab2_add lab2_add.csv lab2_list lab2_list.csv
	-./lab2_add --threads=1 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=20 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=40 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=80 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=1000 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --yield >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100000 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=20 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=80 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=1000 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --yield >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100000 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=20 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=40 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=80 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=1000 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --yield >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100000 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=20 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=40 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=80 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=1000 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --yield >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100000 --yield >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=20 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=40 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=80 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=100 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=1000 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10000 >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=100000 >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=1000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=1000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=1000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=1000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --yield --sync=m >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=1000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=1000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=1000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=1000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --yield --sync=c >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=100 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=1000 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=100 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=1000 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=100 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=1000 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=100 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=1000 --yield --sync=s >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10000 --sync=m >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --sync=m >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --sync=m >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --sync=m >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --sync=m >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10000 --sync=s >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --sync=s >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --sync=s >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --sync=s >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --sync=s >>lab2_add.csv
	-./lab2_add --threads=1 --iterations=10000 --sync=c >>lab2_add.csv
	-./lab2_add --threads=2 --iterations=10000 --sync=c >>lab2_add.csv
	-./lab2_add --threads=4 --iterations=10000 --sync=c >>lab2_add.csv
	-./lab2_add --threads=8 --iterations=10000 --sync=c >>lab2_add.csv
	-./lab2_add --threads=12 --iterations=10000 --sync=c >>lab2_add.csv
	-./lab2_list --threads=1 --iterations=10 >>lab2_list.csv
	-./lab2_list --threads=1 --iterations=100 >>lab2_list.csv
	-./lab2_list --threads=1 --iterations=1000 >>lab2_list.csv
	-./lab2_list --threads=1 --iterations=10000 >>lab2_list.csv
	-./lab2_list --threads=1 --iterations=20000 >>lab2_list.csv
	# conflicts w/o yielding
	-./lab2_list --threads=2 --iterations=10 >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=100 >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=1000 >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=10 >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=100 >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=1000 >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=10 >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=100 >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=1000 >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=10 >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=100 >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=1000 >>lab2_list.csv
	# generate insert conflicts
	-./lab2_list --threads=2 --iterations=2 --yield=i >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=4 --yield=i >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=8 --yield=i >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=16 --yield=i >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=32 --yield=i >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=2 --yield=i >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=4 --yield=i >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=8 --yield=i >>lab2_list.csv
	-./lab2_list --threads=4 --iterations=16 --yield=i >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=2 --yield=i >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=4 --yield=i >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=8 --yield=i >>lab2_list.csv
	-./lab2_list --threads=8 --iterations=16 --yield=i >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=2 --yield=i >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=4 --yield=i >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=8 --yield=i >>lab2_list.csv
	-./lab2_list --threads=12 --iterations=16 --yield=i >>lab2_list.csv
	# generate delete conflicts
	-./lab2_list --threads=2 --iterations=2 --yield=d >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=4 --yield=d >>lab2_list.csv
	-./lab2_list --threads=2 --iterations=8 --yield=d >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=16 --yield=d >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=32 --yield=d >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=2 --yield=d >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=4 --yield=d >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=8 --yield=d >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=16 --yield=d >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=2 --yield=d >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=4 --yield=d >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=8 --yield=d >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=16 --yield=d >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=2 --yield=d >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=4 --yield=d >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=8 --yield=d >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=16 --yield=d >> lab2_list.csv
	# generate insert/lookup conflicts
	-./lab2_list --threads=2 --iterations=2 --yield=il >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=4 --yield=il >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=8 --yield=il >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=16 --yield=il >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=32 --yield=il >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=2 --yield=il >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=4 --yield=il >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=8 --yield=il >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=16 --yield=il >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=2 --yield=il >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=4 --yield=il >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=8 --yield=il >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=16 --yield=il >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=2 --yield=il >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=4 --yield=il >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=8 --yield=il >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=16 --yield=il >> lab2_list.csv
	# generate delete/lookup conflicts
	-./lab2_list --threads=2 --iterations=2 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=4 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=8 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=16 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=2 --iterations=32 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=2 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=4 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=8 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=4 --iterations=16 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=2 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=4 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=8 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=8 --iterations=16 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=2 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=4 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=8 --yield=dl >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=16 --yield=dl >> lab2_list.csv
	# demonstrate the efficacy of mutex and spin-lock synchronization
	-./lab2_list --threads=12 --iterations=32 --yield=i --sync=m >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=d --sync=m >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=il --sync=m >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=dl --sync=m >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=i --sync=s >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=d --sync=s >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=il --sync=s >> lab2_list.csv
	-./lab2_list --threads=12 --iterations=32 --yield=dl --sync=s >> lab2_list.csv
